aerospike/aerospike-kubernetes-operator

- Jenkinsfile
- build/Dockerfile
- deploy/operator.yaml
- pkg/controller/admission/mutate_cluster.go
- pkg/controller/aerospikecluster/aero_helper.go
- pkg/controller/aerospikecluster/aerospikecluster_controller.go
- pkg/controller/aerospikecluster/controller_helper.go
- pkg/controller/utils/utils.go
- test/e2e/setup_operator_test.yaml
- version/version.go
* Podspec triggered rolling restart without an update on the second run. Fixed.
* Pending pods caused rack deletes to get stuck. Fixed by ignoring pending pods during scaledown, rack delete, rolling restart, and version upgrade.
* Removed hardcoded version from versions. Passed to build using build args.
* Dangling rack stateful sets that failed for some reason and then deleted by users even before being added to status, cleaned up now.
* Operator deployment has a readiness probe to ensure operator webhook service redirects correctly to the operator leader instance.
* Dangling pods where cleanup fails are retried and cleaned up.
> 1.0.0 fixes

- helm-charts/aerospike-kubernetes-operator/templates/deployment.yaml
changes indent to nindent so that YAML is properly formed when actually specifying resource requests and limits with the helm chart values.
> Fix helm chart indent issue with resources in deployment.yaml

- api/v1alpha1/aerospikecluster_mutating_webhook.go
- api/v1alpha1/aerospikecluster_validating_webhook.go
- go.mod
- go.sum
- pkg/configschema/4_0_0.go
- pkg/configschema/4_1_0.go
- pkg/configschema/4_2_0.go
- pkg/configschema/4_3_0.go
- pkg/configschema/4_3_1.go
- pkg/configschema/4_4_0.go
- pkg/configschema/4_5_0.go
- pkg/configschema/4_5_1.go
- pkg/configschema/4_5_2.go
- pkg/configschema/4_5_3.go
- pkg/configschema/4_6_0.go
- pkg/configschema/4_7_0.go
- pkg/configschema/4_8_0.go
- pkg/configschema/4_9_0.go
- pkg/configschema/5_0_0.go
- pkg/configschema/5_1_0.go
- pkg/configschema/5_2_0.go
- pkg/configschema/5_3_0.go
- pkg/configschema/5_4_0.go
- pkg/configschema/5_5_0.go
This PR is continue of https://github.com/aerospike/aerospike-management-lib/pull/7
This will change all schemas to support lists for tls-authenticate-client.
Also added validation to prevent mixing "false" or "any" values with other values in a list.
Also added some extra validation on tls configuration preventing set tls params without providing a valid tls-name.
> Support list for tls-authenticate-client.

- helm-charts/aerospike-cluster/README.md
Indentation for the storage stanza in the rack config example is fixed
Signed-off-by: Jean-Francois Weber-Marx <jf.webermarx@criteo.com>
Signed-off-by: Jean-Francois Weber-Marx <jfwm@hotmail.com>
> Fix rackConfig in cluster helm chart README.md

- controllers/scripts/common-env.sh
The hostname is not guaranteed to be the pod name.
Since the operator already creates the pod with an env with
the pod name we can use that instead
> Use $MY_POD_NAME instead of hostname

- helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml
- helm-charts/aerospike-cluster/values.yaml
- In aerospike cluster helm chart the value of multiPodPerHost true if not defined: {{ .Values.multiPodPerHost | default true }}
- When the value of multiPodPerHost is set to false in a chart, the value defined about gives true.
- To fix that, this change set the attribute in values.yaml to true.
Signed-off-by: Jean-Francois Weber-Marx <jf.webermarx@criteo.com>
> Fix multiPodPerHost helm char default override

- api/v1alpha1/aerospikecluster_mutating_webhook.go
- api/v1alpha1/aerospikecluster_validating_webhook.go
- api/v1alpha1/utils.go
- controllers/aero_info_calls.go
- controllers/client_policy.go
- controllers/configmap.go
- controllers/pod.go
- controllers/scripts/create-aerospike-conf.sh
- controllers/statefulset.go
Here is current logic:
- All AS ports are hardcoded in [constants here](https://github.com/aerospike/aerospike-kubernetes-operator/blob/1a3f18c7a01f54b9392cd3832b650bb3a5886378/api/v1alpha1/utils.go#L23-L39).
- All these ports are injected into AS config in [web hook](https://github.com/aerospike/aerospike-kubernetes-operator/blob/1a3f18c7a01f54b9392cd3832b650bb3a5886378/api/v1alpha1/aerospikecluster_mutating_webhook.go#L307-L368). Thus nobody can set other values.
- The same constants are also used to specify ports in [pod's specs](https://github.com/aerospike/aerospike-kubernetes-operator/blob/38a528566e31e986f8f869d7b326547a7a9345e1/controllers/statefulset.go#L850-L921).
- Also these consts are used [to establish connections to AS …
> Unhardcode port values.

- helm-charts/aerospike-cluster/templates/aerospike-cluster-rbac.yaml
Without it, it will create collision when deploying multiple Aerospike cluster
in the same kubernetes cluster.
The ClusterRole and ClusterRoleBinding don't belong to a namespace
and helm doesn't know to which cluster it belongs to
> Add releaseName in the RBAC definition

- config/samples/storage/eks_ssd_storage_class.yaml
Fixing sample for storage class for EKS.
Without this binding mode PV may be created in a wrong zone.
> Fix volumeBindingMode for EKS SSD storage class.

- controllers/rack.go
- controllers/statefulset.go
- pkg/utils/utils.go
Anti-affinity rules include rack label. This could allow pods from a different rack to be scheduled in single pod per host case if the other rack is also on the same zone and region.
> Ignored rack-label for anti-affinity rules

- api/v1beta1/aerospikecluster_types.go
- api/v1beta1/zz_generated.deepcopy.go
- config/crd/bases/asdb.aerospike.com_aerospikeclusters.yaml
- config/samples/hdd_dim_storage_cluster_cr.yaml
- controllers/pvc.go
- controllers/rack.go
- controllers/reconciler.go
- controllers/scripts/create_pod_status_patch.py
- controllers/statefulset.go
- pkg/utils/utils.go
- test/cluster_helper.go
- test/security_context_test.go
- Injected sidecars like istio are ignored in volume checks.
- Allowed older volume name annotation.
- Renamed initializedVolumePaths status to initializedVolumes retaining compatibility with 2.0.0-rc1
> Allowed injected sidecars

- helm-charts/aerospike-kubernetes-operator/templates/aerospike-cluster-rbac.yaml
This right is needed to do fast restart
bash /etc/aerospike/refresh-cmap-restart-asd.sh am6-aerospikes99-preprod aerospikes99-23
+++ realpath /etc/aerospike/refresh-cmap-restart-asd.sh
++ dirname /etc/aerospike/refresh-cmap-restart-asd.sh
+ script_dir=/etc/aerospike
+ cd /etc/aerospike
+ '[' -z am6-aerospikes99-preprod ']'
+ '[' -z aerospikes99-23 ']'
+ export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/etc/aerospike
+ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/etc/aerospike
+ mkdir -p configmap
+ chmod +x ./kubernetes-configmap-exporter
+ ./kubernetes-configmap-exporter am6-aerospikes99-preprod aerospikes99-23 configmap
panic: configmaps "aerospikes99-23" is forbidden: User "system:serviceaccount:am6-aerospikes99-preprod:aerospike-operator-co …
> Add rights to read configmaps for aerospike-operator-controller-manager svc account

- controllers/access_control.go
- controllers/reconciler.go
- go.sum
A fix for OPS-5449, which works but runs the risk of not dropping users if there are failures and changes in a quick
succession.
A proper fix requires the server to mark users and roles as external in client queries.
> [OPS-5449] Only drop user's and roles that were previously created by the operator

- api/v1beta1/utils.go
- controllers/configmap.go
- controllers/scripts/create-aerospike-conf.sh
- go.mod
Currently, we set address for heartbeat and fabric regardless if port was configured. Making it conditional, since today we do not require to set ports.
> Set address in config only if port is set.

- api/v1beta1/aerospikecluster_validating_webhook.go
- go.mod
- go.sum
- test/cluster_helper.go
- test/cluster_test.go
- test/test_client.go
Allow adding ns dynamically. If ns uses persistent storage then storage should be
given in CR's storage section while deploying the cluster.
(enables encryption at rest)
> Allow updating ns storage-engine after deployment.

- api/v1beta1/aerospikecluster_types.go
Setting fsGroup to root groupID(0) in pod securityContext. Aerospike InitContainer needs write permission to the volumes to create directories. so fsGroup needs to set in open shift enviornment specially.
> [KO-116] Adding fsGroup to root groupID(0) in pod security context

- controllers/scripts/copy-templates.sh
- controllers/scripts/initialize.sh
Long running init scripts were being run from the config map folder. If and when the ConfigMap refreshed, the directory working directory for a running directory would deleted and a new one created. The running script would then not find files, when referenced WRT to its current working directory which would have been leaned up.
Fixed by running scripts from a copy of the scripts coming from configmaps.
> [KO-126] Prevent config map refresh break long running init scripts

- .snyk
Vulnerability scanning was failing because of the error mentioned [here](https://security.snyk.io/vuln/SNYK-RHEL8-KRB5LIBS-3121841). Hence ignored this error as solution was not available with RHEL at that point of time under PR [Ignoring KRB5LIBS-3121841 vulnerability. by tanmayja · Pull Request #164 · aerospike/aerospike-kubernetes-operator](https://github.com/aerospike/aerospike-kubernetes-operator/pull/164) and [Ignore vulnerability that has not fix as of now. by tanmayja · Pull Request #161 · aerospike/aerospike-kubernetes-operator](https://github.com/aerospike/aerospike-kubernetes-operator/pull/161).
Now RHEL has fixed the issue above version 0:1.18.2-22.el8_7 or higher. Hence reverting the changes done before to ignore this error.
> [KO-150] Ignored SNYK-RHEL8-KRB5LIBS-3121841 vulnerability issue.

- .golangci.yml
- .pre-commit-config.yaml
- Added golangci-lint configuration file
- Integrated pre-commit tool for git hooks
- Install pre-commit using `pip install pre-commit` or `brew install pre-commit`
- Install required git hooks by running `pre-commit install` from the repo root
NOTE: To bypass githook during git commit, append  `--no-verify` param in the git commit command
Pre-commit Ref: https://pre-commit.com/#install
> KO-153: Integrated pre-commit git-hooks

- .snyk
- test/rack_utils.go
Ignoring this issue in vulnerability scanning as fix is not yet available.
https://security.snyk.io/vuln/SNYK-RHEL8-LIBKSBA-3232176
> Ignoring SNYK-RHEL8-LIBKSBA-3232176 vulnerability

- Jenkinsfile
- test/cleanup-test-namespace.sh
After upgrading `envtest` version, `setup-envtest` downloads some binaries in bin/k8s. 
In Jenkins, user does not have the write permission to this directory due to which cleanup is failing.
Hence adding the permission and cleaning the workspace after Jenkins run finished.
> Giving write permission to bin/k8s in jenkins for it to be cleaned.

- helm-charts/aerospike-cluster/README.md
- helm-charts/aerospike-cluster/templates/aerospike-cluster-cr.yaml
- helm-charts/aerospike-cluster/values.yaml
This change makes possible the addition of custom labels to the aerospike cluster custom ressource at deployement time using Helm
> Add custom label to aerospike cluster cr via helm chart

- api/v1/aerospikecluster_mutating_webhook.go
- api/v1/aerospikecluster_types.go
- api/v1/aerospikecluster_validating_webhook.go
- api/v1/utils.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/asdb.aerospike.com_aerospikeclusters.yaml
- config/manifests/bases/aerospike-kubernetes-operator.clusterserviceversion.yaml
- config/rbac/role.yaml
- controllers/aerospikecluster_controller.go
- controllers/poddistruptionbudget.go
- controllers/reconciler.go
- helm-charts/aerospike-kubernetes-operator/crds/customresourcedefinition_aerospikeclusters.asdb.aerospike.com.yaml
- helm-charts/aerospike-kubernetes-operator/templates/aerospike-operator-manager-clusterrole.yaml
- test/poddisruptionbudget_test.go
Added tests for disablePDB flag
> [KO-321] [KO-320] Added a flag to disable PDB

- internal/controller/cluster/pod.go
- pkg/utils/pod.go
Added reasons to logs for unscheduled pods
> KO-322: Added reasons to logs for unscheduled pods

- api/v1/aerospikecluster_types.go
- config/crd/bases/asdb.aerospike.com_aerospikeclusters.yaml
- config/samples/storage/aks_ssd_storage_class.yaml
- config/samples/storage/eks_ssd_storage_class.yaml
- config/samples/storage/gke_ssd_storage_class.yaml
- helm-charts/aerospike-kubernetes-operator/crds/customresourcedefinition_aerospikeclusters.asdb.aerospike.com.yaml
- internal/controller/cluster/aero_info_calls.go
- internal/controller/cluster/pod.go
- internal/webhook/v1/storage.go
- test/cluster/local_pvc_delete_test.go
- test/cluster/storage_wipe_test.go
- Skip pod restart due to networkPolicy change
- Skip pod restart after AKO upgrade due to both to TLS migration
> AKO 4.1.0 bug fixes
